POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Truman Show Wiki",
    "author": "Wikipedia",
    "url": "https://en.wikipedia.org/wiki/Truman_Show",
    "likes": 4000
}


###

DELETE  http://localhost:3003/api/blogs/6170c020f25ec945f5d83e53

### 

PUT http://localhost:3003/api/blogs/61719ebbe49567a7bbef0105
Content-Type: application/json

{
    "title": "Truman",
    "author": "Wikipedia",
    "url": "https://en.wikipedia.org/wiki/Truman_Show",
    "likes": 4004
}

###

POST  http://localhost:3003/api/users
Content-Type: application/json

{
    "user": "POMO",
    "name": "Taavi Tampio",
    "password": "123kingi123"
}